#!/usr/bin/env python3

import argparse
from uaa_bot.bot import UAABot

parser = argparse.ArgumentParser(
    description="The uaa-bot cli.",
)

subparsers = parser.add_subparsers(
    dest="command", help="Run <command> help for more information."
)


## Bulk deactivation
parser_bulk_deactivate = subparsers.add_parser(
    "bulk-deactivate",
    help=(
        f"Deactivate accounts that have not been logged in many months ",
        f"without sending email notification.",
    ),
)

parser_bulk_deactivate.add_argument(
    "-d",
    "--days-ago",
    dest="days_ago",
    type=int,
    help="End of time range for the n number of days ago.",
    required=True,
    default=180,
)

parser_bulk_deactivate.add_argument(
    "-r",
    "--day-range",
    dest="day_range",
    type=int,
    help="The n number of days to create a range before the --days-ago param.",
    required=True,
    default=365,
)

parser_bulk_deactivate.add_argument(
    "-t",
    "--title",
    dest="title",
    type=str,
    help="The title of the summary of the bulk deactivation.",
    required=False,
    default="Bulk deactivation",
)


## Notify 10 days to deactivation
parser_notify_10_days = subparsers.add_parser(
    "notify-10-days",
    help="Notify users with email to log in in 10 days or be deactivated.",
)


## Notify 1 day to deactivation
parser_notify_1_day = subparsers.add_parser(
    "notify-1-day",
    help="Notify users with email to log in in 1 day or be deactivated.",
)

## Notify and deactivate
parser_notify_deactivate = subparsers.add_parser(
    "notify-deactivate",
    help="Notify users with email they have be deactivated after 90 days without login.",
)

if __name__ == "__main__":
    args = parser.parse_args()
    bot = UAABot()

    if args.command == "bulk-deactivate":
        print(bot)
        print(args.title)
        print(args.day_range)
        print(args.days_ago)
        # summary = bot.deactivate_users(
        #     days_ago=args.days_ago, days_range=args.day_range, summary_title=args.title
        # )
        # print(summary)

    if args.command == "notify-10-days":
        summary = bot.notify_deactivation_in_10_days()
        print(summary)

    if args.command == "notify-1-day":
        summary = bot.notify_deactivation_in_1_day()
        print(summary)

    if args.command == "notify-deactivate":
        summary = bot.notify_and_deactivate()
        print(summary)
