FROM python:3.8-slim as base

# When building locally, these should be set to your UID/GID.  That way, any
# files written to the $PWD mount will be owned by you.  This is not
# necessary (or wanted) when building in Concourse.
ARG UID=2000
ARG GID=2000
ARG USER=app

# In case the host user's GID is already in the base image.
RUN grep -q ":$GID:" /etc/group \
 || groupadd --gid="$GID" "$USER"

RUN useradd \
      --home-dir="/home/$USER" \
      --no-log-init \
      --create-home \
      --shell=/bin/bash \
      --gid=$GID \
      --uid=$UID \
      --no-user-group \
      --non-unique \
      "$USER"

RUN apt update \
 && apt -y upgrade \
 && apt install -y --no-install-recommends \
      build-essential \
      libpq-dev \
      curl \
      gnupg2 \
      procps \
      git

# Install local python packages
RUN pip install --upgrade pip
COPY pip-tools/dev-requirements.txt ./pip-tools/
RUN pip install -r pip-tools/dev-requirements.txt

WORKDIR /app
RUN chown "$UID:$GID" .
USER $UID:$GID

COPY . .

ENV PATH=/usr/local/bin:$PATH
ENV ENV=local
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt

ENTRYPOINT ["bash", "-c"]
CMD ["bash"]
