#!/usr/bin/env bash

cd /app || (echo "Cannot find /app directory"; exit 2)
set -xeuo pipefail

if [[ "$#" -ge 1 ]] && [[ "$1" == "watch" ]]; then
  shift
  ptw --spool=1000 -n -c -w -- -Werror -vv "$@"
else
  python -m pytest -Werror -vv "$@"
fi
