###########
# Jobs

jobs:

- name: test-bot
  plan:
  - get: src-repository
    resource: src-repository
    trigger: true
  - task: run-tests
    file: src-repository/ci/test-runner.yml
  on_failure:
    put: slack
    params:
      text: |
        :x: FAILED to pass tests for uaa-bot
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-info-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))
  on_success:
    put: slack
    params:
      text: |
        :white_check_mark: Successfully passed tests for uaa-bot
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-info-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))


###########
# Resources

resources:

- name: src-repository
  type: git
  icon: github-circle
  check_every: 10s
  source:
    uri: https://github.com/cloud-gov/((name))
    branch: ((git-branch))

- name: slack
  type: slack-notification
  source:
    url: ((slack-webhook-url))

################
# Resource Types

resource_types:

- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
