###########
# Jobs

jobs:

- name: test-bot
  plan:
  - in_parallel:
    - get: src-repository
      resource: src-repository
      trigger: true
  - task: run-tests
    file: src-repository/ci/test-runner.yml
  on_failure:
    put: slack
    params:
      text: |
        :x: FAILED to pass tests for uaa-bot
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-info-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))
  on_success:
    put: slack
    params:
      text: |
        :white_check_mark: Successfully passed tests for uaa-bot
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-info-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))

- name: bot-development-list-expired
  plan:
  - in_parallel:
    - get: src-repository
      resource: src-repository
      passed: [test-bot]
  - task: run-bot-development-list-expired
    file: src-repository/ci/bot-development-list-expired.yml
    params:
      UAA_BASE_URL: ((uaa-base-url-development))
      UAA_CLIENT_ID: ((uaa-client-id-development))
      UAA_CLIENT_SECRET: ((uaa-client-secret-development))
  on_failure:
    put: slack
    params:
      text: |
        :x: FAILED to list expired users with uaa-bot
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-info-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))
  on_success:
    put: slack
    params:
      text: |
        :white_check_mark: Successfully listed expired users with uaa-bot
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-info-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))

- name: bot-development-bulk-deactivate
  plan:
  - in_parallel:
    - get: src-repository
      resource: src-repository
      passed: [test-bot]
    - get: daily-timer
      trigger: true
  - task: run-bot-development-bulk-deactivate
    file: src-repository/ci/bot-development-bulk-deactivate.yml
    params:
      DAYS_AGO: 90
      NUMBER_DAYS_BEFORE: 1000
      SUMMARY_TITLE: "Users deactivated from development"
      UAA_BASE_URL: ((uaa-base-url-development))
      UAA_CLIENT_ID: ((uaa-client-id-development))
      UAA_CLIENT_SECRET: ((uaa-client-secret-development))
  on_failure:
    put: slack
    params:
      text: |
        :x: FAILED to bulk deactivate users with uaa-bot
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-info-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))
  on_success:
    put: slack
    params:
      text: |
        :white_check_mark: Successfully bulk deactivated users with uaa-bot
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-info-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))

- name: bot-staging-list-expired
  plan:
  - in_parallel:
    - get: src-repository
      resource: src-repository
      passed: [test-bot]
  - task: run-bot-staging-list-expired
    file: src-repository/ci/bot-staging-list-expired.yml
    params:
      UAA_BASE_URL: ((uaa-base-url-staging))
      UAA_CLIENT_ID: ((uaa-client-id-staging))
      UAA_CLIENT_SECRET: ((uaa-client-secret-staging))
  on_failure:
    put: slack
    params:
      text: |
        :x: FAILED to list expired users with uaa-bot
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-info-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))
  on_success:
    put: slack
    params:
      text: |
        :white_check_mark: Successfully listed expired users with uaa-bot
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-info-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))

- name: bot-staging-bulk-deactivate
  plan:
  - in_parallel:
    - get: src-repository
      resource: src-repository
      passed: [test-bot]
    - get: daily-timer
      trigger: true
  - task: run-bot-staging-bulk-deactivate
    file: src-repository/ci/bot-staging-bulk-deactivate.yml
    params:
      DAYS_AGO: 90
      NUMBER_DAYS_BEFORE: 1000
      SUMMARY_TITLE: "Users deactivated from staging"
      UAA_BASE_URL: ((uaa-base-url-staging))
      UAA_CLIENT_ID: ((uaa-client-id-staging))
      UAA_CLIENT_SECRET: ((uaa-client-secret-staging))
  on_failure:
    put: slack
    params:
      text: |
        :x: FAILED to bulk deactivate users with uaa-bot
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-info-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))
  on_success:
    put: slack
    params:
      text: |
        :white_check_mark: Successfully bulk deactivated users with uaa-bot
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-info-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))

- name: bot-production-list-expired
  plan:
  - in_parallel:
    - get: src-repository
      resource: src-repository
      passed: [test-bot]
  - task: run-bot-production-list-expired
    file: src-repository/ci/bot-production-list-expired.yml
    params:
      UAA_BASE_URL: ((uaa-base-url-production))
      UAA_CLIENT_ID: ((uaa-client-id-production))
      UAA_CLIENT_SECRET: ((uaa-client-secret-production))
  on_failure:
    put: slack
    params:
      text: |
        :x: FAILED to bulk deactivate users with uaa-bot
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-info-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))
  on_success:
    put: slack
    params:
      text: |
        :white_check_mark: Successfully bulk deactivated users with uaa-bot
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-info-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))

- name: bot-production-notify-1-day
  plan:
  - in_parallel:
    - get: src-repository
      resource: src-repository
      passed: [test-bot]
    # - get: daily-timer
    #   trigger: true
  - task: run-bot-production-notify-1-day
    file: src-repository/ci/bot-production-notify-1-day.yml
    params:
      SMTP_HOST: ((smtp-host))
      SMTP_PORT: ((smtp-port))
      SMTP_USER: ((smtp-user))
      SMTP_PASS: ((smtp-pass))
      SMTP_FROM: ((smtp-from))
      SMTP_CERT: ((smtp-cert))
      UAA_BASE_URL: ((uaa-base-url-production))
      UAA_CLIENT_ID: ((uaa-client-id-production))
      UAA_CLIENT_SECRET: ((uaa-client-secret-production))
  on_failure:
    put: slack
    params:
      text: |
        :x: FAILED to notify users with 1 day until deactivation with uaa-bot
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-info-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))
  on_success:
    put: slack
    params:
      text: |
        :white_check_mark: Successfully notified users with 1 day until deactivation with uaa-bot
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-info-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))

- name: bot-production-notify-10-days
  plan:
  - in_parallel:
    - get: src-repository
      resource: src-repository
      passed: [test-bot]
    # - get: daily-timer
    #   trigger: true
  - task: run-bot-production-notify-10-days
    file: src-repository/ci/bot-production-notify-10-days.yml
    params:
      SMTP_HOST: ((smtp-host))
      SMTP_PORT: ((smtp-port))
      SMTP_USER: ((smtp-user))
      SMTP_PASS: ((smtp-pass))
      SMTP_FROM: ((smtp-from))
      SMTP_CERT: ((smtp-cert))
      UAA_BASE_URL: ((uaa-base-url-production))
      UAA_CLIENT_ID: ((uaa-client-id-production))
      UAA_CLIENT_SECRET: ((uaa-client-secret-production))
  on_failure:
    put: slack
    params:
      text: |
        :x: FAILED to notify users with 10 days until deactivation with uaa-bot
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-info-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))
  on_success:
    put: slack
    params:
      text: |
        :white_check_mark: Successfully notified users with 10 days until deactivation with uaa-bot
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-info-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))

- name: bot-production-notify-deactivate
  plan:
  - in_parallel:
    - get: src-repository
      resource: src-repository
      passed: [test-bot]
    # - get: daily-timer
    #   trigger: true
  - task: run-bot-production-notify-deactivate
    file: src-repository/ci/bot-production-notify-deactivate.yml
    params:
      SMTP_HOST: ((smtp-host))
      SMTP_PORT: ((smtp-port))
      SMTP_USER: ((smtp-user))
      SMTP_PASS: ((smtp-pass))
      SMTP_FROM: ((smtp-from))
      SMTP_CERT: ((smtp-cert))
      UAA_BASE_URL: ((uaa-base-url-production))
      UAA_CLIENT_ID: ((uaa-client-id-production))
      UAA_CLIENT_SECRET: ((uaa-client-secret-production))
  on_failure:
    put: slack
    params:
      text: |
        :x: FAILED to deactivate users with uaa-bot
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-info-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))
  on_success:
    put: slack
    params:
      text: |
        :white_check_mark: Successfully deactivate users with uaa-bot
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-info-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))

###########
# Resources

resources:

- name: src-repository
  type: git
  icon: github-circle
  check_every: 10s
  source:
    uri: https://github.com/cloud-gov/((name))
    branch: ((git-branch))

- name: daily-timer
  type: time
  source:
    start: 6:00 AM
    stop: 7:00 AM
    location: America/New_York

- name: slack
  type: slack-notification
  source:
    url: ((slack-webhook-url))

################
# Resource Types

resource_types:

- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
